[package]
name = "ed25519-compact"
version = "0.1.9"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "A small, self-contained, wasm-friendly Ed25519 implementation"
readme = "README.md"
keywords = ["crypto", "ed25519", "eddsa", "signature"]
repository = "https://github.com/jedisct1/rust-ed25519-compact"
homepage = "https://github.com/jedisct1/rust-ed25519-compact"
categories = ["algorithms", "cryptography", "no-std", "wasm"]
license = "ISC"

[features]
default = ["random", "std"]
random = ["getrandom"]
traits = ["ed25519"]
self-verify = []
std = []

[dependencies]
getrandom = { version = "0.2", optional = true }
ed25519 = { version = "1.0", optional = true }

[dev-dependencies]
getrandom = "0.2"
